spring:
  application:
    name: TmService
  config:
    import: "configserver:http://localhost:8080"
  kafka:
    bootstrap-servers: "localhost:9092"

org:
  quartz:
    job-store-type: memory
    jobStore:
      class: "org.quartz.simpl.RAMJobStore"