server:
  port: 9090

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: ClientAuthService
          uri: lb://ClientAuthService
          predicates:
            - Path=/auth/client/**
        - id: ApplicationService
          uri: http://localhost:8082
          predicates:
            - Path=/applications/**
          filters:
            - name: JwtClientAuth
            - RewritePath=/applications(?<segment>/?.*), $\{segment}


jwt_secret: "q*#!R**Djtyx5#dXogXV!rDVg*9tA4%b#dXogXV!rDVg*9tA4%bq*#!R**Djtyx5#dXogXV!"