server:
  port: 9090

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: ClientAuthService
          uri: lb://ClientAuthService
          predicates:
            - Path=/auth/client/**
          filters:
            - RewritePath=/auth/client(?<segment>/?.*), $\{segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
            - name: CircuitBreaker
              args:
                name: ClientAuthService
                fallbackUri: forward:/fallback
        - id: UserService
          uri: lb://UserAuthService
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}
            - name: JwtUserAuth
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
            - name: CircuitBreaker
              args:
                name: UserService
                fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
        - id: UserAuthService
          uri: lb://UserAuthService
          predicates:
            - Path=/auth/user/**
          filters:
            - RewritePath=/auth/user(?<segment>/?.*), $\{segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
            - name: CircuitBreaker
              args:
                name: UserAuthService
                fallbackUri: forward:/fallback
        - id: ApplicationServiceClient
          uri: lb://ApplicationService
          predicates:
            - Path=/applications/client/**
          filters:
            - RewritePath=/applications/client(?<segment>/?.*), /client/$\{segment}
            - name: JwtClientAuth
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
            - name: CircuitBreaker
              args:
                name: ApplicationServiceClient
                fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
        - id: ApplicationServiceUser
          uri: lb://ApplicationService
          predicates:
            - Path=/applications/user/**
          filters:
            - RewritePath=/applications/user(?<segment>/?.*), /user/$\{segment}
            - name: JwtUserAuth
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
            - name: CircuitBreaker
              args:
                name: ApplicationServiceUser
                fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms


client_jwt_secret: "q*#!R**Djtyx5#dXogXV!rDVg*9tA4%b#dXogXV!rDVg*9tA4%bq*#!R**Djtyx5#dXogXV!"
user_jwt_secret: "WmqVtL38_+dX&dAS1c*-I(#ccRdZEzeX.Dy7.NDWbUq9E#1?8b/t6gw'SO0iTdA"

management:
  tracing:
    sampling:
      probability: 1.0


resilience4j:
  circuitbreaker:
    instances:
      sampahService:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 3000            #10 seconds
        registerHealthIndicator: true
  timelimiter:
    instances:
      sampahServie:
        timeoutDuration: 2s