server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: ClientAuthService
          uri: lb://ClientAuthService
          predicates:
            - Path=/auth/client/**
        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
          filters:
            - name: JwtClientAuth


jwt_secret: "q*#!R**Djtyx5#dXogXV!rDVg*9tA4%b#dXogXV!rDVg*9tA4%bq*#!R**Djtyx5#dXogXV!"