spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/clients"
    username: "root"
    password: "Test123!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "true"
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0