spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/loans"
    username: "admin"
    password: "admin"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "true"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: "localhost:9092"
server:
  port: 8086

management:
  tracing:
    sampling:
      probability: 1.0
